name: dart_synth
description: A sandbox for audio synth experimentation in Dart.
version: 0.0.2
repository: https://github.com/maks/dart_synth
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  libao: ^0.2.0
  wasm: 
    git:
      url: https://github.com/dart-lang/wasm.git
      ref: main    


dev_dependencies:
  pedantic: ^1.10.0
